# Generated by Django 5.2.13 on 2026-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_signed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
    ]
